---
  kind: pipeline
  type: docker
  name: release-aiostreams

  steps:
  - name: create-release-archive
    image: walkero/docker4amigavbcc:latest-base
    commands:
      - cd /drone/src
      - mkdir aiostreams
      - mv ./docs ./aiostreams/
      - mv ./simplejson ./aiostreams/
      - mv ./*.py ./aiostreams/
      - mv ./*.py.examples ./aiostreams/
      - mv ./*.info ./aiostreams/
      - mv ./*.md ./aiostreams/docs/
      - mv LICENSE ./aiostreams/docs/
      - mkdir release
      - lha -aq2o6 aiostreams-${DRONE_TAG}.lha aiostreams/
#   - name: deploy-on-repo
#     image: plugins/github-release
#     settings:
#       api_key:
#         from_secret: GITHUB_RELEASE_API_KEY
#       files:
#         - "./aiostreams-*.lha"
#       title: "${DRONE_TAG} release"
  - name: prepare-aminet-release
    image: walkero/docker4amigavbcc:latest-base
    commands:
      - mkdir aminet-release
      - cp aiostreams-${DRONE_TAG}.lha ./aminet-release/aiostreams.lha
      - cp aminet.readme ./aminet-release/aiostreams.readme
  - name: upload-to-aminet
    image: cschlosser/drone-ftps
    environment:
      FTP_USERNAME:
        from_secret: FTP_USERNAME
      FTP_PASSWORD:
        from_secret: FTP_PASSWORD
      PLUGIN_HOSTNAME: walkero.duckdns.org:21
      PLUGIN_SRC_DIR: /aminet-release
      PLUGIN_DEST_DIR: ./new
      PLUGIN_SECURE: "false"
      PLUGIN_VERIFY: "false"

  trigger:
    event:
      include:
        - push
