---
  kind: pipeline
  type: docker
  name: release-aiostreams

  steps:
  - name: create-archive
    pull: always
    image: walkero/docker4amigavbcc:latest-base
    commands:
      - cd /drone/src
      - mkdir aiostreams
      - mv ./docs ./aiostreams/
      - mv ./simplejson ./aiostreams/
      - mv ./*.py ./aiostreams/
      - mv ./*.py.examples ./aiostreams/
      - mv ./*.info ./aiostreams/
      - mv ./*.md ./aiostreams/docs/
      - mv LICENSE ./aiostreams/docs/
      - lha -aq2o6 aiostreams-${DRONE_TAG}.lha aiostreams/
  - name: deploy-on-repo
    pull: always
    image: plugins/github-release
    settings:
      api_key:
        from_secret: GITHUB_RELEASE_API_KEY
      files:
        - "aiostreams-*.lha"
      title: "${DRONE_TAG} release"

  trigger:
    event:
      include:
        - tag
