---
kind: pipeline
type: docker
name: test-release-aiostreams

workspace:
  path: /drone/src

steps:
- name: create-test-archive
  image: walkero/lha-on-docker:latest
  commands:
    - mkdir aiostreams
    - mv ./docs ./aiostreams/
    - mv ./simplejson ./aiostreams/
    - mv ./*.py ./aiostreams/
    - mv ./*.py.examples ./aiostreams/
    - mv ./*.info ./aiostreams/
    - mv ./*.md ./aiostreams/docs/
    - mv LICENSE ./aiostreams/docs/
    - sed -i "s/RELEASE_DATE/$(date +'%Y-%m-%d')/" ./aiostreams/docs/aiostreams.guide ./aiostreams/docs/CHANGELOG.md ./aiostreams/cmn.py
    - sed -i "s/VERSION_TAG/TEST/" ./aiostreams/docs/aiostreams.guide ./aiostreams/docs/CHANGELOG.md ./aiostreams/cmn.py ./aminet.readme ./os4depot.readme
    - lha -aq2o6 aiostreams-TEST.lha aiostreams/
# - name: Prepare test release
#   image: walkero/lha-on-docker:latest
#   environment:
#     OS4DEPOT_PASSPHRASE: 
#         from_secret: OS4DEPOT_PASSPHRASE
#   commands:
#     - mkdir test-release
#     - cp aiostreams-TEST.lha ./test-release/aiostreams.lha
#     - cp os4depot.readme ./test-release/os4depot.readme
#     - cp aminet.readme ./test-release/aminet.readme
# - name: Upload to TEST FTP
#   image: cschlosser/drone-ftps
#   environment:
#     FTP_USERNAME:
#       from_secret: MVBETAFTP_USERNAME
#     FTP_PASSWORD:
#       from_secret: MVBETAFTP_PASSWORD
#     PLUGIN_HOSTNAME: mediavault.amiga-projects.net:21
#     PLUGIN_SRC_DIR: /test-release
#     PLUGIN_DEST_DIR: ./web/betas
#     PLUGIN_SECURE: "false"
#     PLUGIN_VERIFY: "false"
#     PLUGIN_CLEAN_DIR: "false"

trigger:
  branch:
    include:
    - master
    - ci-cd2
  event:
    include:
    - push
